config/routes.rb
Rails.application.routes.draw do

  resources :dbfields
  resources :dbtables
  resources :requests
  resources :sections
  resources :chapters
  resources :books

  #resources :searches
  resources :resources
  resources :site_images
  resources :site_documents
  resources :post_documents
  devise_for :users
  resources :posts
  resources :comments, :path_prefix => '/:commentable_type/:commentable_id'

  get 'publish', to: 'visitors#publish', as: 'publish'
  get 'moveup', to: 'sections#moveup', as: 'moveup'
  get 'movedown', to: 'sections#movedown', as: 'movedown'
  get 'staffguide', to: 'visitors#staff_guide', as: 'staffguide'
  get 'granteeguide', to: 'visitors#grantee_guide', as: 'granteeguide'
  get 'adminguide', to: 'visitors#admin_guide', as: 'adminguide'
  get 'submit', to: 'requests#submit', as: 'submit'
  get 'requestdash', to: 'requests#dashboard', as: 'requestdash'
  root 'requests#index'


  resources :users

end

app/models/request.rb
class Request < ActiveRecord::Base
  extend EnumerateIt
  has_enumeration_for :requesttype
  has_enumeration_for :origin
  has_enumeration_for :nea_decision

  acts_as_commentable
  has_many :comments




  has_many :site_documents
  has_many :site_images

  belongs_to :user, :foreign_key => :approver_id
  belongs_to :user, :foreign_key => :responder_id
  belongs_to :user, :foreign_key => :creator_id
  belongs_to :user, :foreign_key => :decided_by

  has_many :requestlogs

  def production
    if deployed_on
      return true
    end
  end

  def testing
    if tested_on
      return true
    end
  end
  def development
    if developed_on
      return true
    end
  end

  def approved
    if decided_on and nea_decision == 1
      return true
    end
  end

  def rejected
    if decided_on and nea_decision == 2
      return true
    end
  end

  def onhold
    if decided_on and nea_decision == 4
      return true
    end
  end

  def addinfo
    if decided_on and nea_decision == 3
      return true
    end
  end

  def responded
    if  responded_on and !decided_on
      return true
    end
  end

  def submitted
    if !responded_on and submitted_on
      return true
    end
  end


  def presubmit
    if !submitted_on
      return true
    end
  end

  def fullid
    if self.origin == 1
        vid = '<span style="font-weight: bold; color: green">CR-' + self.id.to_s + '</span>'
     else
       vid = '<span style="font-weight: bold; color: darkblue">PR-' + self.id.to_s + '</span>'
    end
    return self.raw(vid)
  end

  def raw(stringish)

    stringish.to_s.html_safe

  end




def textstatus

  if self.production
    t='Deployed to Production'
  elsif self.testing
    t = 'Testing'
  elsif self.development
    t = 'In Development'
  elsif self.approved
    t = 'NEA Approved'
  elsif self.rejected
    t = 'NEA Rejected'
  elsif self.onhold
    t = 'On Hold/No Decision'
  elsif self.addinfo
    t = 'More Info Required/No Decision'
  elsif self.responded
    t = 'Pillar Response'
  elsif self.submitted
    t = 'NEA Submit to Pillar'
  elsif self.presubmit
    t = 'NEA Create'
  else
    t = 'N/A'
  end
  return t


end








end

app/models/requesttype.rb
class Requesttype < EnumerateIt::Base
  associate_values(
      :defect  => 1,
      :enhancement  => 2

  )
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  def dashboard
    @newrequests = Request.where('submitted_on is NULL')
    @pendingresponse = Request.where('submitted_on is not NULL and responded_on is NULL')
    @pendingnea = Request.where('responded_on is not NULL and decided_on is NULL')
    approved = Request.where('decided_on is not NULL and nea_decision = ?', 1)
    @ondeck = approved.where('deployed_on is NULL and tested_on is NULL and developed_on is NULL')
    @deployed = approved.where('deployed_on is not NULL')
    @ontesting = approved.where('deployed_on is NULL and tested_on is not NULL')
    @indevelopment = approved.where('deployed_on is NULL and tested_on is NULL and developed_on is not NULL')
    @rejected = Request.where('decided_on is not NULL and nea_decision = ?', 2)
    @holding = Request.where('decided_on is not NULL and nea_decision in (?)', [3,4])






    render 'dashboard'
  end








  # GET /requests/1
  # GET /requests/1.json
  def show
    @comments = Comment.where('(commentable_type = ? and commentable_id = ?)', 'Request', @request.id)
    @new_comment = Comment.new

    @reqdocuments = SiteDocument.where('documentable_type = ? and documentable_id = ?', 'request', @request.id)
    @new_site_document = SiteDocument.new

    @reqimages = SiteImage.where('imageable_type = ? and imageable_id = ?', 'request', @request.id)
    @new_site_image = SiteImage.new



    @thisstatus = @request.textstatus

    @requestlog = Requestlog.where('request_id = ?', @request.id).order('created_at DESC')
    if @request.creator_id
      @creator = User.find(@request.creator_id)
    end

    if @request.submitter_id
      @submitter = User.find(@request.submitter_id)
    end

    if @request.responder_id
      @responder = User.find(@request.responder_id)
    end
    if @request.decided_by
      @decider = User.find(@request.decided_by)
    end
  end





  # GET /requests/new
  def new
    @request = Request.new
    @request.origin = params[:origin]
  end

  # GET /requests/1/edit
  def edit
    puts @request
    @status = @request.textstatus
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)


    respond_to do |format|
      if @request.save
        Requestlog.create(request_id: @request.id, user_id: current_user.id, reqaction: 'created')
        format.html { redirect_to requests_path, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end




def submit
  @request=Request.find(params[:request_id])
  puts '----------------------------------------------------------------------------------ddddddddddddddddddddddd----------------------'
  puts @request

  if params[:reqaction] == 'clone'
    newsubject = 'Cloned from ' + @request.subject
    newrequest = Request.create(subject: newsubject, origin: @request.origin, creator_id: current_user.id)

  else

    if params[:reqaction] == 'submit'
      @request.submitted_on = Date.today
      @request.submitter_id = current_user.id
      @request.responded_on = nil
    elsif params[:reqaction] == 'recommend'
        @request.submitted_on = Date.today
        @request.submitter_id = current_user.id
        @request.responded_on = Date.today
        @request.responder_id = current_user.id

    elsif params[:reqaction] == 'respond'
      @request.responded_on = Date.today
      @request.responder_id = current_user.id
    elsif params[:reqaction] == 'decide'
      @request.decided_on = Date.today

      @request.decided_by = current_user.id
    elsif params[:reqaction] == 'develop'
      @request.developed_on = Date.today
      @request.tested_on = nil
      @request.deployed_on = nil

    elsif params[:reqaction] == 'test'
      @request.tested_on = Date.today
    elsif params[:reqaction] == 'deploy'
      @request.deployed_on =Date.today

    end
    @request.save
    Requestlog.create(request_id: @request.id, user_id: current_user.id, reqaction: params[:reqaction], nea_decision: @request.nea_decision)


  end
  respond_to do |format|
  format.html { redirect_to @request, notice: 'Request was successfully updated.' }
  end

end







  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:name, :oldcode, :submitted_on, :role, :requestor, :requestor_email, :submitter_id, :requesttype, :urgent, :deployed_on, :origin,
                                      :subject, :description, :pillar_response, :impact_hour, :impact_duration, :impact_schedule, :tested_on, :developed_on, :responded_on,:responder_id,
                                      :approved, :approver_id, :approved_on, :nea_decision, :decided_on, :decisiontext, :conditions, :decided_by, :modernize, :creator_id)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<style>

  tinput {width: 90%}
</style>
<div class="container">

    <div class="panel panel-default">

    <div class="panel-heading"><h2><%= @panelheader %></h2>
    <%if params[:action] == "edit" %><h2><strong><%= @request.subject %></strong></h2><% end %></div>

  <div class="panel-body">

    <%= form_for(@request, :class => "form-horizontal") do |f| %>
        <% if params[:action] == 'new' %>
            <%= f.hidden_field :origin, :value => params[:origin] %>
        <% end %>
        <%=  f.hidden_field :creator_id, :value => current_user.id %>

          <% if @request.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

              <ul>
              <% @request.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

        <div class="form-horizontal">

            <% if @request.presubmit or current_user.role == 1 %>


              <div class="form-group">
                <%= f.label :subject, :class => "col-sm-2 control-label" %>
                <div class="col-sm-10">
                  <%= f.text_field :subject, :size => 100, :class => "form-control" %>

                </div>
              </div>


            <div class="form-group">
              <%= f.label :oldcode, :class => "col-sm-2 control-label" %>
              <div class="col-sm-10">
                <div style="width: 80px">
                <%= f.text_field :oldcode, :class => "form-control" %>
                </div>
              </div>
            </div>


            <div class="form-group">
              <%= f.label 'Requestor', :class => "col-sm-2 control-label" %>
              <div class="col-sm-3">
                <%= f.text_field :requestor, :size => 40, :class => "form-control" %>
              </div>
              <%= f.label 'Email', :class => "col-sm-1 control-label" %>
              <div class="col-sm-3">
                <%= f.text_field :requestor_email, :size => 50, :class => "form-control" %>
              </div>
              <%= f.label 'Role', :class => "col-sm-1 control-label" %>
              <div class="col-sm-2">
                <%= f.select(:acprsrole, Acprsrole.to_a, :class => "form-control", :label => false ) %>
              </div>
            </div>



              <div class="form-group">
                <%= f.label :requesttype, :class => "col-sm-2 control-label" %>
                <div class="col-sm-10">
                  <%= f.select(:requesttype, Requesttype.to_a, :class => "form-control", :label => false ) %>

                </div>
              </div>

              <div class="form-group">
                <%= f.label :urgent, :class => "col-sm-2 control-label" %>
                <div class="col-sm-1">
                  <%= f.check_box :urgent, :class => "form-control pull-left" %>

                </div>
              </div>


              <div class="form-group">
                <%= f.label :description, :class => "col-sm-2 control-label" %>
                <div class="col-sm-10">
                  <%= f.text_area :description, :id => "descedit", :cols => "80", :rows => "15" %>

                </div>
              </div>





        <% end %>
<% if (@request.submitted or (@request.presubmit and @request.origin == 2)) or current_user.role == 1 %>


              <div class="form-group">
                <%= f.label :pillar_response, :class => "col-sm-2 control-label" %>
                <div class="col-sm-10">
                  <%= f.text_area :pillar_response, :id => "descedit", :cols => "80", :rows => "15" %>

                </div>
              </div>

              <div class="form-group">
                <%= f.label :impact_hour, :class => "col-sm-2 control-label" %>
                <div class="col-sm-10">
                  <%= f.number_field :impact_hour %>

                </div>
              </div>


              <div class="form-group">
                <%= f.label 'Duration Impact', :class => "col-sm-2 control-label" %>
                <div class="col-sm-10">
                  <%= f.text_field :impact_duration %>

                </div>
              </div>


              <div class="form-group">
                <%= f.label 'Schedule Impact', :class => "col-sm-2 control-label" %>
                <div class="col-sm-10">
                  <%= f.text_field :impact_schedule %>
                </div>
              </div>


    <% end %>

    <% if @request.responded  or current_user.role == 1 %>



  <div class="field">
    <%= f.label :nea_decision %><br>
    <%= f.select(:nea_decision, NeaDecision.to_a, :class => "form-control", :label => false, :include_blank => true) %>

  </div>


        <div class="form-group">
          <%= f.label 'Decision Notes' %><br>

            <%= f.text_area :decisiontext, :id => "decideedit", :cols => "80", :rows => "6" %>
                  </div>


        <div class="form-group">
          <%= f.label 'Approval Conditions' %><br>
            <%= f.text_area :conditions, :id => "conditionsedit", :cols => "80", :rows => "6" %>

        </div>




        <% end %>
  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
        </div>
<% end %>
</div>
  </div>

</div>
</div>
<script>
  $(function() {
    $('#edit').froalaEditor()
  });
  $(function() {
    $('#adminedit').froalaEditor()
  });
</script>

app/views/requests/edit.html.erb
<% if params[:origin] == 2 %>
    <% @panelheader = 'Edit Recommendation' %>
<% else %>
    <% @panelheader = 'Edit Request' %>

<% end %>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<% if [1,3].include? current_user.role %>
<%= link_to 'Submit New Request', new_request_path(:origin => 1), :class => "btn btn-small btn-success" %>
<% end %>

<% if [1,4].include? current_user.role %>
<%= link_to 'Submit New Recommendation', new_request_path(:origin => 2), :class => "btn btn-small btn-primary" %>
<% end %>





<h1>Listing Requests</h1>

<table id="requesttable"  class="hover" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>ID</th>
      <th>OldID</th>
      <th>Status</th>
      <th>Decision</th>
      <th>Subject</th>
      <th>Requestor</th>
      <th>Submit Date</th>

      <th>Response</th>

      <th>Decided on</th>


    </tr>
  </thead>

  <tbody>
  
  
  
  
  
  
  
  
    <% @requests.each do |request| %>



      <% thisstatus = request.textstatus %>





      <% if request.creator_id %>
      <% creator = User.find(request.creator_id) %>
      <% end %>

         <% if request.responder_id  %>
      <% responder = User.find(request.responder_id) %>
      <% end %>
         <% if request.decided_by  %>
      <% decider = User.find(request.decided_by) %>
      <% end %>


      <tr>
        <td><%= request.fullid %></td>
        <td><%= request.oldcode %></td>

        <td>
      <strong><%= request.textstatus %></strong>

        </td>
        <td>

          <%= request.nea_decision_humanize if request.nea_decision %>

        </td>
        <td><%= link_to request.subject, request %><% if request.urgent == true %> <span style="color:red; font-weight: bold;">Urgent!</span><% end %></td>
        <td><%= request.requestor %></td>

        <td><%= request.submitted_on.strftime("%m/%d") if request.submitted_on %></td>
        <td><%= request.responded_on.strftime("%m/%d") if request.responded_on %></td>



        <td><%= request.decided_on.strftime("%m/%d") if request.decided_on  %></td>


      </tr>
    <% end %>
  </tbody>
</table>






<br>

























<script>
    $(document).ready(function() {
        $('#requesttable').DataTable();
    } );
</script>

app/views/requests/new.html.erb
<% if params[:origin] == 2 %>
    <% @panelheader = 'New Recommendation' %>
<% else %>
    <% @panelheader = 'New Request' %>
<% end %>




<%= render 'form' %>

<%= link_to 'Back', sections_path %>

app/views/requests/show.html.erb
<% if @request.nea_decision == 1 %>
    <% dlight='darkblue' %>
    <% dtext='#fff' %>
<% elsif @request.nea_decision == 2 %>
    <% dlight='red' %>
    <% dtext='#fff' %>
<% elsif @request.nea_decision == 3 %>
    <% dlight='green' %>
    <% dtext='#fff' %>
<% elsif @request.nea_decision == 4 %>
    <% dlight='gray' %>
    <% dtext='#000' %>
<% else %>
    <% dlight='white' %>
    <% dtext='#000' %>

<% end %>


<div class="container">
  <%= @request.origin_humanize %><br>
  <h3> <% if @request.urgent == true %><strong>Urgent</strong><% end %> </h3>

  <h2> <%= @request.fullid %> : <%= @request.subject %></h2>

  <div class="row">
  
  <div class="col-md-6">




    <p>
      <strong>Status:</strong>

      <strong><%= @thisstatus %></strong>

    </p>
    <p>
  
  
  
  <p>
    <strong>Type:</strong>
    <%= @request.requesttype_humanize if @request.requesttype %>
  </p>
  <p>

  <p>
    <strong>Description:</strong>
    <%= @request.description %>
  </p>



  <p>
    <strong>Record Created:</strong>
    <%= @request.created_at %>  by: <%= @creator.email %>
  </p>

    <p>
      <strong>Request Submitted to Pillar:</strong>
      <%= @request.submitted_on %>  by: <%= @submitter.email if @request.submitter_id %>
    </p>

  <hr>
    <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-default">
        <div class="panel-heading">Attachments</div>
        <div class="panel-body">
          <% @reqdocuments.each do |doc| %>
              <%= link_to doc.document_file_name , doc.document.url(:original, false) %>
              <%= doc.document_updated_at %><br>
          <% end %>
          <%= simple_form_for @new_site_document do |form| %>
              <%= form.hidden_field :documentable_id, :value => @request.id %>
              <%= form.hidden_field :documentable_type, :value => 'request' %>
              <%= form.input :document, as: :file %>
              <%= form.button :submit, :value => 'Upload Document', :class => "mb-sm btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
<hr>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">Pillar Response</div>
      <div class="panel-body">
        <p>
          <strong>Responded:</strong>
          <% if @request.responded_on %>
          <%= @request.responded_on %>  by: <%= @responder.email if @responder.email %>
        <% end %>
              </p>


        <p>
          <strong>Initial Response:</strong>
          <%= @request.pillar_response.html_safe if @request.pillar_response %>
        </p>

        <p>
          <strong>Impact hour:</strong>
          <%= @request.impact_hour %>
        </p>

        <p>
          <strong>Impact duration:</strong>
          <%= @request.impact_duration %>
        </p>

        <p>
          <strong>Impact schedule:</strong>
          <%= @request.impact_schedule %>
        </p>

      </div>
    </div>




<hr>

    <div class="panel panel-default">
      <div class="panel-heading">NEA Decision</div>
      <div class="panel-body">
  <p>
    <strong>Decision:</strong>
     <span style="color: <%= dtext %>; background-color: <%= dlight %>">
       <% if @request.nea_decision %>
      <%= @request.nea_decision_humanize %>
      </span>
      <% else %>
           Pending
           <% end %>

           <br>
       <% if @request.decided_on %>
    <%= @request.decided_on %>  by: <%= @decider.email if @request.decided_by %>
           <% end %>
  </p>

  <p>
    <strong>Decisiontext:</strong>
    <%= @request.decisiontext %>
  </p>
  <p>
    <strong>Conditions:</strong>
    <%= @request.conditions %>
  </p>

      </div>
    </div>




    <p>
  <strong>Move to Testing Server:</strong>
   <%= @request.tested_on if @request.tested_on %>
</p>


  <p>
    <strong>Deployed to Production:</strong>
    <%= @request.deployed_on if @request.deployed_on %>
  </p>





  </div>
    <div class="col-md-6">
      <div class="col-md-12">
    <h3>Actions</h3>

        <STRONG><%= link_to 'Back to Requests List', requests_path %></STRONG>
        <BR>        <BR>

      <% if @request.deployed_on %>
          <%= link_to 'Create New Request from Issue', submit_path(:request_id => @request.id, :reqaction => 'clone'), 'data-toggle' => 'modal', :class => "btn btn-default" %><br><br>
          <%= link_to 'Return to Develop', submit_path(:request_id => @request.id, :reqaction => 'develop'), 'data-toggle' => 'modal', :class => "btn btn-success" %><br><br>

    <% elsif @request.decided_on %>

           <% if @request.nea_decision == 1 %>
                <% if current_user.role != 3 %>
                   <% if !@request.developed_on %>
                      <%= link_to 'Begin Development', submit_path(:request_id => @request.id, :reqaction => 'develop'), 'data-toggle' => 'modal', :class => "btn btn-success" %><br><br>
                  <% elsif @request.developed_on and !@request.tested_on %>
                      <%= link_to 'Moved to Testing', submit_path(:request_id => @request.id, :reqaction => 'test'), 'data-toggle' => 'modal', :class => "btn btn-success" %><br><br>
                   <% elsif @request.developed_on and @request.tested_on and !@request.deployed_on %>
                      <%= link_to 'Deployed to Production', submit_path(:request_id => @request.id, :reqaction => 'deploy'), 'data-toggle' => 'modal', :class => "btn btn-success" %><br><br>
                      <%= link_to 'Return to Development', submit_path(:request_id => @request.id, :reqaction => 'develop'), 'data-toggle' => 'modal', :class => "btn btn-success" %><br><br>
                   <% end %>
                <% end %>
        <% elsif @request.nea_decision == 2 %>
                  <%= link_to 'Revised to New Request', submit_path(:request_id => @request.id, :reqaction => 'clone'), 'data-toggle' => 'modal', :class => "btn btn-primary" %><br><br>
        <% elsif @request.nea_decision == 3 or @request.nea_decision == 4 %>

                <% if current_user.role != 4 %>
             <%= link_to 'Approve Request', submit_path(:request_id => @request.id, :reqaction => 'approve'), 'data-toggle' => 'modal', :class => "btn btn-success" %><br><br>
             <%= link_to 'Reject Request', submit_path(:request_id => @request.id, :reqaction => 'reject'), 'data-toggle' => 'modal', :class => "btn btn-danger" %><br><br>
             <%= link_to 'Create New Request', submit_path(:request_id => @request.id, :reqaction => 'clone'), 'data-toggle' => 'modal', :class => "btn btn-default" %><br><br>
                <% end %>
        <% end %>
    <% else %>


          <% if @request.responded_on %>
                <% if current_user.role != 4 %>
                      <%= link_to 'Edit', edit_request_path(@request), :class => "btn btn-primary" %> <br><br>
                      <% if !@request.decided_on %>
                      <%= link_to 'Confirm Decision', submit_path(:request_id => @request.id, :reqaction => 'decide'), 'data-toggle' => 'modal', :class => "btn btn-success" %>
                        Set as: <strong>  <%= @request.nea_decision_humanize %></strong>
                        <br><br>
                      <% end %>
                <% end %>

          <% elsif !@request.responded_on and @request.submitted_on %>

                <% if current_user.role != 3 or current_user.role ==1 %>
              <%= link_to 'Edit', edit_request_path(@request), :class => "btn btn-primary" %> <br><br>
              <%= link_to 'Respond to NEA', submit_path(:request_id => @request.id, :reqaction => 'respond'), 'data-toggle' => 'modal', :class => "btn btn-success" %><br><br>
<% end %>

          <% elsif !@request.submitted_on or current_user.role ==1 %>
              <%= link_to 'Edit', edit_request_path(@request), :class => "btn btn-primary" %> <br><br>
              <% if @request.origin == 1 %>
                <%= link_to 'Submit to Pillar', submit_path(:request_id => @request.id, :reqaction => 'submit'), 'data-toggle' => 'modal', :class => "btn btn-success" %><br><br>
              <% else %>
                <%= link_to 'Submit to NEA', submit_path(:request_id => @request.id, :reqaction => 'recommend'), 'data-toggle' => 'modal', :class => "btn btn-success" %><br><br>
              <% end %>


    <% end %>
       <% end %>

<% if current_user.role == 1 %>

        <%= link_to 'Destroy', @request, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
        <% end %>


      </div>
      <div class="col-md-12">
        <h3>History</h3>
        <table class="table table-striped">
          <thead>

          <td>Date</td>
          <td>Action</td>
          <td>User</td>
                  </thead>

          <tbody>
         <% @requestlog.each do |log| %>
          <tr>
              <td><%= log.created_at %></td>
            <td><strong><%= log.reqaction %>

            <% if log.reqaction == 'decide' %> <strong><%= log.nea_decision_humanize if log.nea_decision %></strong> <% end %>
            </strong>
            </td>

            <td><%= log.user.email %></td>
            </tr>




        <% end %>
          </tbody>
</table>


      </div>
      <div class="col-md-12">
        <h3>Comments</h3>

        <table class="table table-striped">
          <thead>

          <td>Date</td>
          <td>Action</td>
          <td>User</td>
          </thead>
            <tbody>

        <% @comments.each do |comment| %>
              <td>
                <td><%= comment.created_at %> <%= comment.user.email %><br>
                <%= comment.body %></td>

              </tr>





        <% end %> <!-- end show comments -->
            </tbody>
</table>

        <div class="alert alert-info fade in">

          <% if current_user %>

              <h3>Add Comment</h3>

              <%= simple_form_for @new_comment do |f| %>
                  <%= f.hidden_field :commentable_id, :value => @request.id %>
                  <%= f.hidden_field :commentable_type, :value => 'request' %>
                  <%= f.text_area :body, :class => "form-control", :rows => "7" %>
                  <%= f.submit 'Submit' %>
              <% end %>


          <% end %>
        </div>





      </div>

    </div>

  </div>


</div>