config/routes.rb
Rails.application.routes.draw do

  resources :dbfields
  resources :dbtables
  resources :requests
  resources :sections
  resources :chapters
  resources :books

  #resources :searches
  resources :resources
  resources :site_images
  resources :site_documents
  resources :post_documents
  devise_for :users
  resources :posts
  resources :comments, :path_prefix => '/:commentable_type/:commentable_id'

  get 'publish', to: 'visitors#publish', as: 'publish'
  get 'moveup', to: 'sections#moveup', as: 'moveup'
  get 'movedown', to: 'sections#movedown', as: 'movedown'
  get 'staffguide', to: 'visitors#staff_guide', as: 'staffguide'
  get 'granteeguide', to: 'visitors#grantee_guide', as: 'granteeguide'
  get 'adminguide', to: 'visitors#admin_guide', as: 'adminguide'
  get 'submit', to: 'requests#submit', as: 'submit'
  get 'requestdash', to: 'requests#dashboard', as: 'requestdash'
  root 'requests#index'


  resources :users

end

app/models/post.rb
class Post < ActiveRecord::Base

  translates :title, :description

  has_many :site_documents
  has_many :site_images



  acts_as_commentable
  has_many :comments
end

app/models/search.rb
class Search < ActiveRecord::Base
  has_many :searches_technicalareas, :dependent => :destroy
  has_many :technicalareas, :through => :searches_technicalareas

  has_many :searches_targetgroups, :dependent => :destroy
  has_many :targetgroups, :through => :searches_targetgroups

  has_many :searches_organizations, :dependent => :destroy
  has_many :organizations, :through => :searches_organizations

  has_many :searches_series, :dependent => :destroy
  has_many :series, :through => :searches_series

end

app/views/resources/_form.html.erb
<style>
  .chkpanel {
      font-size: 9px;
      font-weight: normal;


  }



</style>



<div class="panel panel-default">
  <div class="panel-body">


<%= form_for(@resource) do |f| %>
        <%= hidden_field_tag :locale, I18n.locale %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="col-sm-6">

    <div class="field">
      <%= f.label :is_featured %><br>
      <%= f.check_box :is_featured %>
    </div>

    <div class="field">
      <%= f.label "Resource" %><br>
      <%= f.text_field :title, :size => "75" %>
    </div>

    <div class="field">
      <%= f.label :body %><br>
      <%= f.text_area :body, :cols => "75", :rows => "15" %>
    </div>

        <% if I18n.locale == :en %>

    <div class="field">
      <%= f.label 'Language' %><br>
      <%= f.select(:language, Language.to_a, :include_blank => true, :class => "form-control") %>
    </div>


    <div class="field">
      <%= f.label :submitter %><br>
      <%= f.text_field :submitter %>
    </div>

    <div class="field">
      <%= f.label :published_at %><br>
      <%= f.date_select :published_at %>
    </div>

    <div class="field">
      <%= f.label :position %><br>
      <%= f.text_field :position %>
    </div>

    <div class="field">
      <%= f.label "Organization [select]" %><br>

      <%= f.collection_select(:organization_id, Organization.all, :id, :name, include_blank: true, :class => "form-control") %>
    </div>

    <div class="field">
      <%= f.label "Organization" %><br>
      <%= f.text_field :orgname %>
    </div>
    <div class="field">
      <%= f.label :submitter_email %><br>
      <%= f.text_field :submitter_email %>
    </div>
    <div class="field">
      <%= f.label :submitter_phone %><br>
      <%= f.text_field :submitter_phone %>
    </div>

        <div class="field">
          <%= f.label "Project [select]" %><br>

          <%= f.collection_select(:project_id, Project.all, :id, :name, include_blank: true, :class => "form-control") %>
        </div>


    <div class="field">
      <%= f.label :mepi_project %><br>
      <%= f.text_field :mepi_project %>
    </div>
    <div class="field">
      <%= f.label :mepi_project_number %><br>
      <%= f.text_field :mepi_project_number %>
    </div>
    <div class="field">
      <%= f.label :focus_women %><br>
      <%= f.check_box :focus_women %>
    </div>
    <div class="field">
      <%= f.label :focus_youth %><br>
      <%= f.check_box :focus_youth %>
    </div>

<% end %>




  </div>


  <% if I18n.locale == :en %>

  <div class="col-sm-3 chkpanel">
    <label class="label">Technical Areas</label>
    <div class="row">
      <%= hidden_field_tag "resource[technicalarea_ids][]", nil %>
      <% @technicalarea_list.all.each do |area| %>
          <%= check_box_tag "resource[technicalarea_ids][]", area.id,
                            @resource.technicalarea_ids.include?(area.id), id: dom_id(area) %>
          <%= label_tag dom_id(area), area.name %><br>
      <% end %>

    </div>

  </div>
  <div class="col-sm-3 chkpanel">
    <label class="label">Target Groups</label>
    <div class="row">
      <%= hidden_field_tag "resource[targetgroup_ids][]", nil %>
      <% @targetgroup_list.all.each do |group| %>
          <%= check_box_tag "resource[targetgroup_ids][]", group.id,
                            @resource.targetgroup_ids.include?(group.id), id: dom_id(group) %>
          <%= label_tag dom_id(group), group.name %><br>
      <% end %>

    </div>
  </div>



    
    <div class="col-sm-3 chkpanel">
    <label class="label">Tags</label>
    <div class="row">
      <%= hidden_field_tag "resource[tag_ids][]", nil %>
      <% @tag_list.all.each do |tg| %>
          <%= check_box_tag "resource[tag_ids][]", tg.id,
                            @resource.tag_ids.include?(tg.id), id: dom_id(tg) %>
          <%= label_tag dom_id(tg), tg.name %><br>
      <% end %>
    
    </div>
    </div>
      
      
      
<% end %>

</div>















    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


    Basic panel example
  </div>
</div>

app/views/resources/_resources_table.html.erb
<script>
    $(document).ready(function() {
        $('#example').DataTable();
    } );
</script>


<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4><%= @tabletitle %></h4>
      </div>
      <div class="panel-body">
        <table id="example" class="cell-border" cellspacing="0" width="100%">
          <thead>
          <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Categories</th>


            <th>Organization</th>

            <th>Focus</th>


          </tr>
          </thead>
          <tbody>
          <% @resources.each do |resource| %>


              <tr>

                <td><%= resource.id %></td>
                <td>
                <% if !resource.series_id.nil? %>
                      <small class="color: orange"><%= resource.series.name %></small><br>
                      <% end %>
                  <%= link_to resource do %><%= resource.title %><% end %></td>
                <td>
                  <em>Technical:</em> <% resource.technicalareas.each do |ta| %>
                      <%= ta.name %>
                  <% end %><br>
                  <em>Targets:</em>  <% resource.targetgroups.each do |tg| %>
                      <%= tg.name %>
                  <% end %>

                      </td>

                <td><%#= resource.orgname %><BR>
                <small class="color: orange"><% if !resource.organization_id.nil? %><%= resource.organization.name %><% end %></small>
                </td>


                <td>
                  <% if resource.focus_women == true %>
                      <button type="button" class="btn btn-primary">Women</button>
                  <% end %>
                  <% if resource.focus_youth == true %>
                      <button type="button" class="btn btn-primary">Youth</button>
                  <% end %>
</td>

              </tr>
          <% end %>

          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<!-- END DATATABLE 1 -->

app/views/resources/admin_check_orgs.html.erb
helllo















<%= form_tag edit_multiple_resources_path, method: :get do %>
<table  cellspacing="0" width="100%">
  <thead>
  <tr>
    <th></th>
    <th>NID</th>
    <th>Title</th>
    <th>Organization</th>

  </tr>
  </thead>
  <tbody>
  <% @resources.each do |resource| %>

      <tr>

        <td><%= resource.nid %></td>
        <td><%= resource.title %></td>


        <td><%= check_box_tag "resource_ids[]", resource.id %></td>
        <td><%= resource.orgname %></td>
        <td><% if !resource.organization_id.nil? %><%= resource.organization.name %><% end %></td>
        </td>

      </tr>
  <% end %>

  </tbody>
</table>
    <%= submit_tag "Edit Checked" %>
<% end %>

app/views/resources/edit.html.erb
<h3>Editing Resource: <%= @resource.title %></h3>










<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/edit_multiple.html.erb
<%= form_tag update_multiple_resources_path, method: :put do %>


    <% @resources.each do |resource| %>
        <h2><%= resource.title %></h2>
        <%= fields_for "resources[]", resource do |f| %>
            <% if resource.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>
                  <ul>
                    <% resource.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>




              <div class="field">
                <%= f.label "Organization" %><br>
                <%= f.text_field :orgname %>
              </div>

              <div class="field">
                <%= f.label "Organization [select]" %><br>

                <%= f.collection_select(:organization_id, Organization.all, :id, :name, include_blank: true, :class => "form-control") %>
              </div>

            ...
        <% end %>
    <% end %>



    <div class="actions">
      <%= submit_tag "Update" %>
    </div>
<% end %>

app/views/resources/index.html.erb
<style>
  .facetbox {
      font-size: 12px;
      background-color: #fdfdfd;
      padding: 5px;


  }


</style>





<div class="container content">
  <div class="row">
    <div class="col-md-9">
      <!-- Our Services -->
      <div class="headline"><h2>Search Results</h2>



      </div>



      <%= form_tag resources_path, :method => :get do %>
          <p>
            <%= text_field_tag :search_term, params[:search_term] %>
            <%= submit_tag "Search", :name => nil %>
          </p>
      <% end %>








      Search term <span style="color: orangered;"><%= @searchterm %></span><br>
      <% @resources.each do |result| %>



          <strong><%= link_to result do %><%= result.title %><% end %></strong><br>
          <% if !result.series_id.nil? %>
              <small class="color: orange">Series: <%= result.series.name %></small><br>
          <% end %>

          <br>
          <%= result.body %>
          <br>
          <em>Technical:</em> <% result.technicalareas.each do |ta| %> |
              <%= link_to ta.name, ta %>
          <% end %><br>
          <em>Targets:</em>  <% result.targetgroups.each do |tg| %> |
              <%= link_to tg.name, tg %>
          <% end %><br>
          <em>Organization:</em>  <% if !result.organization_id.nil? %> <%= link_to result.organization.name, result.organization %> <% end %><br>
          <em>Series:</em>  <% if !result.series_id.nil? %><%= link_to result.series.name, result.series  %><% end %><br>

<%= I18n.locale %>--------------------

          <%#= render result %>

          ---------<%= result.is_arabic %>----------
          <% if I18n.locale != :en %>
              <% trans_en = Resource::Translation.where('resource_id =? and locale = ?', result.id, 'en') %>
              <% if !trans_en.blank? %>
                  &nbsp;&nbsp;&nbsp;<strong><%= link_to 'English', result %></strong>
              <% end %>
          <% end %>

          <% if I18n.locale != :ar %>
              <% trans_ar = Resource::Translation.where('resource_id =? and locale = ?', result.id, 'ar') %>

              <% if !trans_ar.blank? %>
                  &nbsp;&nbsp;&nbsp;<strong><%= link_to 'Arabic', result %></strong>
              <% end %>
          <% end %>

          <% if I18n.locale != :fr %>
              <% trans_fr = Resource::Translation.where('resource_id =? and locale = ?', result.id, 'fr') %>

              <% if !trans_fr.blank? %>
                  &nbsp;&nbsp;&nbsp;<strong><%= link_to 'French', result %></strong>

              <% end %>
          <% end %>

<%#= debug trans_ar %>
<%#= debug trans_fr %>





          <br><br>
      <% end %>

      <br>


    </div>


    <div class="col-md-3">


      <div id="facets" class="facetbox pull-right">


<h3>Search Results Drilldown</h3>

        <strong>Publish Date</strong>
        <ul>
          <% for row in @search.facet(:publish_month).rows %>
              <li>
                <% if params[:month].blank? %>
                <%= link_to row.value, :month => row.value %> (<%= row.count %>)
                <% else %>
                <strong><%= row.value %></strong> (<%= link_to "remove", :month => nil %>)
                <% end %>
              </li>
          <% end %>
        </ul>
        <strong>Technical Areas</strong>
        <ul>
          <% for row in @search.facet(:technicalarea_ids).rows %>
              <li>
                <%= link_to(row.instance.name, url_for(:technicalarea_id => row.value)) %> (<%= row.count %>)

              </li>
          <% end %>
        </ul>
        <strong>Target Groups</strong>
        <ul>
          <% for row in @search.facet(:targetgroup_ids).rows %>
              <li>
                <%= link_to(row.instance.name, url_for(:targetgroup_id => row.value)) %> (<%= row.count %>)

              </li>
          <% end %>
        </ul>
        <strong>Organizations</strong>
        <ul>
          <% for row in @search.facet(:organization_id).rows %>
              <li>
                <%= link_to(row.instance.name, url_for(:organization_id => row.value)) %> (<%= row.count %>)

              </li>
          <% end %>
        </ul>

      </div>





    </div>



  </div>
</div>

app/views/resources/new.html.erb
<%= debug @resource.language %>


<h2>New Resource</h2>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/search_form.html.erb
<div class="col-sm-12  <%= I18n.locale.to_s %>">
    <div class="panel panel-default">


        <h2 class="pagetitle">Search Maktabat Resources</h2>

        <div class="panel-body">

            <%= form_tag resources_path, :method => 'get' do %>
            <%= hidden_field_tag :locale, I18n.locale %>


            <div class="col-sm-6">

                <div class="field">
                    Keyword Search<br>
                    <%= text_field_tag :search_term %>
                </div>

                <br><br>

                Technical Areas<br>
                <%= select_tag "technicalarea_ids", options_from_collection_for_select(Technicalarea.all, "id", "name"), { :multiple => true, :prompt => "select -->"} %>
                <br><br>

                Target Groups<br>
                <%= select_tag "targetgroup_ids", options_from_collection_for_select(Targetgroup.all, "id", "name"), { :multiple => true, :prompt => "select -->" } %>
                <br><br>

                Organization<br>
                <%= select_tag "organization_ids", options_from_collection_for_select(Organization.all, "id", "name"), { :multiple => true, :prompt => "select -->" }%>
                <br><br>

                Series<br>
                <%= select_tag "series_ids", options_from_collection_for_select(Series.where('id < ?', 35), "id", "name"), {:multiple => true, :prompt => "select -->" } %>
                <br><br>



            </div>
            <div class="col-sm-6">

                <div class="actions">
                    <%= submit_tag "Search", :class => "btn btn-primary" %>
                </div>
                <br>
                <br>
                <%= submit_tag  "Reset the Search Form", :type => "reset" %>
            </div>


            <% end %>
        </div>
    </div>
</div>

app/views/resources/search_results.html.erb
<div class="container content">
  <div class="row">
    <div class="col-md-9">
      <!-- Our Services -->
      <div class="headline"><h2>Search Results</h2></div>

      <h2>Search term <span style="color: orangered;"><%= params[:search] %></span></h2>
      <% @resources.each do |result| %>




          <strong><%= link_to result do %><%= result.title %><% end %></strong><br>
          <% if !result.series_id.nil? %>
              <small class="color: orange">Series: <%= result.series.name %></small><br>
          <% end %>


          <%= result.body %>
          <%#= render result %>

          ---------<%= result.is_arabic %>----------
          <% if I18n.locale != 'en' %>
              <% trans_en = Resource::Translation.where('resource_id =? and locale = ?', result.id, 'en') %>
              <% if !trans_en.blank? %>
                  &nbsp;&nbsp;&nbsp;<strong><%= link_to 'English', result %></strong>
              <% end %>
          <% end %>

          <% if I18n.locale != :ar %>
              <% trans_ar = Resource::Translation.where('resource_id =? and locale = ?', result.id, 'ar') %>

              <% if !trans_ar.blank? %>
                  &nbsp;&nbsp;&nbsp;<strong><%= link_to 'Arabic', result %></strong>
              <% end %>
          <% end %>

          <% if I18n.locale != :fr %>
              <% trans_fr = Resource::Translation.where('resource_id =? and locale = ?', result.id, 'fr') %>

              <% if !trans_fr.blank? %>
                  &nbsp;&nbsp;&nbsp;<strong><%= link_to 'French', result %></strong>

              <% end %>
          <% end %>

<%#= debug trans_ar %>
<%#= debug trans_fr %>





          <br><br>
      <% end %>

      <br>

      <%= link_to 'New Search', new_search_path %>
    </div>

  </div>
</div>
<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>

app/views/resources/show.html.erb
<style>
    .pagetitle {
    color: forestgreen;
    font-size: 32px;
    }
    .description {

    }


</style>

<p id="notice"><%= notice %></p>

<div class="col-sm-12  <%= I18n.locale.to_s %>">
  <div class="panel-heading">

    <div class="col-sm-6  <%= I18n.locale.to_s %>">
    Training Resource:<br>

    <% if !@resource.series_id.nil? %>
        <small class="color: orange">Series: <%= @resource.series.name %></small><br>
    <% end %>

    <h2 class="pagetitle"><%= @resource.title %></h2>
  </div>
    <div class="col-sm-6  <%= I18n.locale.to_s %>">
  <%= link_to 'Edit', edit_resource_path(@resource), :class => "mb-sm btn btn-primary pull-right    " %>
      </div>
</div>


<div class="col-sm-12  <%= I18n.locale.to_s %>">

  <div class="col-sm-6  <%= I18n.locale.to_s %>">

    <div class="panel panel-default">

    <div class="panel-body">


      <div class="description">
        <%= raw(@resource.body) %>
        </div>
<hr>
        <p>
            <strong>Organization:</strong>
            <% if !@resource.organization_id.nil? %>
                <%= link_to @resource.organization do %><%= @resource.organization.name %><% end %>
            <% end %>
            <small><%= @resource.orgname %></small>

        </p>
        <p>
            <strong>Project Name:</strong>

          <% if !@resource.project_id.nil? %>
              <%= link_to @resource.project do %><%= @resource.project.name %><% end %>
          <% end %>
            <small ><%= @resource.mepi_project %></small>
        </p>




      <% if @resource.is_featured == true %>
          <p><button type="button" class="btn btn-default">Featured</button></p>
      <% end %>



        <p>
            <strong>Published:</strong>
            <% if !@resource.published_at.nil? %>
              <%= @resource.published_at.strftime("%F")    %>
              <% end %>

        </p>

        <p>
            <strong>Pages:</strong>
            <%= @resource.number_pages %>
        </p>

      <% if @resource.focus_women == true or @resource.focus_youth == true %>
          <p>
      <div class="btn-group" role="group">
        <button type="button" class="btn btn-default">Focus: </button>
        <% if @resource.focus_women == true %>
        <button type="button" class="btn btn-primary">Women</button>
            <% end %>
        <% if @resource.focus_youth == true %>
        <button type="button" class="btn btn-primary">Youth</button>
        <% end %>
      </div>
          </p>
<% end %>




      <p>
        <strong>Technical Areas:</strong>
        <% @resource.technicalareas.each do |area| %>
            <%= link_to area.name %>
            &nbsp;|&nbsp;
        <% end %>
        </p>

      <p>
        <strong>Target Groups:</strong>
        <% @resource.targetgroups.each do |group| %>
            <%= link_to group.name %>
            &nbsp;|&nbsp;
        <% end %>
      </p>
      <p>
      <strong>Country Origin:</strong>
      <% @resource.countries.each do |country| %>
          <%= link_to country.name %>
          &nbsp;|&nbsp;
      <% end %>
      </p>
      <p>
      <strong>Tags:</strong>
      <% @resource.tags.each do |tag| %>
          <%= link_to tag.name %>
          &nbsp;|&nbsp;
      <% end %>
      </p>




        <%= link_to 'Destroy', @resource, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

</div>
</div>


      <div class="col-sm-6  <%= I18n.locale.to_s %>">


        <div class="col-sm-12">
          <div class="panel panel-default">
            <div class="panel-heading">Attachments</div>
            <div class="panel-body">
              <% @resourcedocuments.each do |doc| %>
                  <%= link_to doc.document_file_name , doc.document.url(:original, false) %>
                  <%= doc.document_updated_at %><br>
              <% end %>
              <%= simple_form_for @new_site_document do |form| %>
                  <%= form.hidden_field :documentable_id, :value => @resource.id %>
                  <%= form.hidden_field :documentable_type, :value => 'resource' %>
                  <%= form.input :document, as: :file %>
                  <%= form.button :submit, :value => 'Upload Document', :class => "mb-sm btn btn-primary" %>
              <% end %>
            </div>
          </div>
        </div>

        <div class="col-sm-12">
          <div class="panel panel-default">
            <div class="panel-heading">Images</div>
            <div class="panel-body">



              <%= form_tag updatelogos_path, method: :put do %>
                  <%= hidden_field_tag :resource_id, @resource.id %>
                  <table border="1">
                  <% @resourceimages.each do |doc| %>
                        <%= fields_for "site_images[]", doc do |f| %>

                        <tr>
                     <td>


                       <%# if doc.is_logo == true %>

                           <%= f.check_box :is_logo %>
                       <%#= f.check_box_tag "site_image_ids[]", doc.id, {:checked => "checked"}  %>
                        <%# else %>
                           <%#= f.check_box_tag "site_image_ids[]", doc.id %>
                       <%# end %>

                     </td>
                      <td><%= image_tag doc.image.url, :width => "50", :class => "pull-right" %></td>
                      <td><%= link_to doc.image_file_name , doc.image.url(:original, false) %></td>
                      <td><%= doc.image_updated_at %></td>
                   </tr>
                            <% end %>
                  <% end %>
                  </table>
                  <%= submit_tag "Update logos" %>
              <% end %>


              <%= simple_form_for @new_site_image do |form| %>
                  <%= form.hidden_field :imageable_id, :value => @resource.id %>
                  <%= form.hidden_field :imageable_type, :value => 'resource' %>
                  <%= form.input :image, as: :file %>
                  <%= form.button :submit, :value => 'Upload Image', :class => "mb-sm btn btn-primary" %>
              <% end %>
            </div>
          </div>
        </div>


        <div class="col-sm-12">
          <div class="panel panel-default">
            <div class="panel-heading">Comments and Ratings</div>
            <div class="panel-body">

              <% !if @mycomments.nil? %>
                  <% @mycomments.each do |comment| %>
                      <div class="people-say margin-bottom-20">
                        <div class="overflow-h">
                          <span><a href="#"> <%= comment.user.email %></a></span>
                          <small class="hex pull-right"><%= comment.created_at %></small>

                          <p><%= comment.body %></p>
                          <%#= comment.commentable_type %>

                        </div>
                      </div>
                  <% end %> <!-- end show comments -->
              <% end %>


              <div class="alert alert-info fade in">

                <%# if current_user %>



                <%= simple_form_for @new_comment do |f| %>
                    <%= f.hidden_field :commentable_id, :value => @resource.id %>
                    <%= f.hidden_field :commentable_type, :value => 'resource' %>
                    <%= f.text_area :body, :class => "form-control", :rows => "7" %>
                    <%= f.submit 'Submit' %>
                <% end %>

                <%# end %>
              </div>
            </div>
          </div>
        </div>




      </div>

</div>
      </div>
  </div>