config/routes.rb
Rails.application.routes.draw do

  resources :dbfields
  resources :dbtables
  resources :requests
  resources :sections
  resources :chapters
  resources :books

  #resources :searches
  resources :resources
  resources :site_images
  resources :site_documents
  resources :post_documents
  devise_for :users
  resources :posts
  resources :comments, :path_prefix => '/:commentable_type/:commentable_id'

  get 'publish', to: 'visitors#publish', as: 'publish'
  get 'moveup', to: 'sections#moveup', as: 'moveup'
  get 'movedown', to: 'sections#movedown', as: 'movedown'
  get 'staffguide', to: 'visitors#staff_guide', as: 'staffguide'
  get 'granteeguide', to: 'visitors#grantee_guide', as: 'granteeguide'
  get 'adminguide', to: 'visitors#admin_guide', as: 'adminguide'
  get 'submit', to: 'requests#submit', as: 'submit'
  get 'requestdash', to: 'requests#dashboard', as: 'requestdash'
  root 'requests#index'


  resources :users

end

app/models/post.rb
class Post < ActiveRecord::Base

  translates :title, :description

  has_many :site_documents
  has_many :site_images



  acts_as_commentable
  has_many :comments
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @postdocuments = SiteDocument.where('documentable_type = ? and documentable_id = ?', 'post', @post.id)
    @new_site_document = SiteDocument.new

    @postimages = SiteImage.where('imageable_type = ? and imageable_id = ?', 'post', @post.id)
    @new_site_image = SiteImage.new

    @comments = Comment.where('commentable_type = ? and commentable_id = ?', 'Post', @post.id).order('created_at desc')
    @new_comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update

    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end







  def updatepostlogos
    @site_images = SiteImage.update(params[:site_images].keys, params[:site_images].values)
    @site_images.reject! { |p| p.errors.empty? }

    redirect_to post_url(params[:post_id])


  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :is_featured, :published_at, )
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<style>
    .pagetitle {
        color: orangered;
        font-size: 16px;
    }
</style>

<div class="col-sm-7">
  <div class="panel panel-default">
    <div class="panel-body">
      <%= form_for(@post) do |f| %>
          <%= hidden_field_tag :locale, I18n.locale %>
          <% if @post.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@post.errors.count, "error") %> prohibited this series from being saved:</h2>

                <ul>
                  <% @post.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>

          <div class="field">
            <%= f.label :title %><br>
            <%= f.text_field :title %>
          </div>
          <div class="field">
            <%= f.label 'Body' %><br>
            <%= f.text_area :description %>
          </div>
          <div class="field">
            <%= f.label :is_featured %><br>
            <%= f.check_box :is_featured %>
          </div>

      <div class="field">
        <%= f.label :published_at %><br>
        <%= f.date_select :published_at %>
      </div>
          <div class="actions">
            <%= f.submit %>
          </div>
      <% end %>

    </div>
  </div>

</div>

        ...
        <%#= form.cktext_area :body, :class => 'someclass', :ckeditor => {:language => 'uk'} %>
        ...
        <%#= form.cktext_area :body, :value => 'Default value', :id => 'sometext' %>
        ...
        <%#= cktext_area :post, :info, :cols => 40, :ckeditor => {:uiColor => '#AADC6E', :toolbar => 'mini'} %>
        ...

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>













<h1>Listing Posts</h1>
<table id="example" class="hover" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Type</th>
      <th>Value</th>
      <th>Start</th>
      <th>End</th>

      <!--<th colspan="3"></th>-->
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post do %><%= post.title %><% end %></td>
        <td><%= post.description %></td>
        <td><%= post.post_type_humanize %></td>
        <td><%= post.post_value %></td>
        <td><%= post.start_date %></td>
        <td><%= post.end_date %></td>

        <!--<td><%#= link_to 'Show', post %></td>
        <td><%#= link_to 'Edit', edit_post_path(post) %></td>
        <td><%#= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

<script>
    $(document).ready(function() {
        $('#example').DataTable();
    } );
</script>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>




<div class="container">
  <p id="notice"><%= notice %></p>
  <!-- Page Heading/Breadcrumbs -->
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header"><%= @post.title %>
        <small></small>
      </h1>
    </div>
  </div>
  <!-- /.row -->

  <!-- Content Row -->
  <div class="row">

    <!-- Blog Post Content Column -->
    <div class="col-lg-8">
      Teaser:
      <p>
        <strong>Name:</strong>
        <%= @post.title %>
      </p>
      <% if @post.is_featured == true %>
          <button type="button" class="btn btn-primary">Featured</button>
      <% end %>
      <p>
        <strong>Description (text):</strong>
        <%= @post.description %>
      </p>
      <p>
        <strong>Published:</strong>
        <% if !@post.published_at.nil? %>
            <%= @post.published_at.strftime("%F")    %>
        <% end %>




      <%= link_to 'Edit', edit_post_path(@post) %> |
      <%= link_to 'Back', posts_path %>


      <hr>

      <!-- Blog Comments -->


      <!-- Posted Comments -->



      <div class="col-sm-6">
        <div class="panel panel-default">
          <div class="panel-heading">Attachments</div>
          <div class="panel-body">
            <% @postdocuments.each do |doc| %>
                <%= link_to doc.document_file_name , doc.document.url(:original, false) %>
                <%= doc.document_updated_at %><br>
            <% end %>
            <%= simple_form_for @new_site_document do |form| %>
                <%= form.hidden_field :documentable_id, :value => @post.id %>
                <%= form.hidden_field :documentable_type, :value => 'post' %>
                <%= form.input :document, as: :file %>
                <%= form.button :submit, :value => 'Upload Document', :class => "mb-sm btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>


      <!-- Images -->

      <div class="col-sm-6">
        <div class="panel panel-default">
          <div class="panel-heading">Images</div>
          <div class="panel-body">





            <%= form_tag updatepostlogos_path, method: :put do %>
                <%= hidden_field_tag :post_id, @post.id %>
                <table border="1">
                  <% @postimages.each do |doc| %>
                      <%= fields_for "site_images[]", doc do |f| %>

                          <tr>
                            <td>


                              <%# if doc.is_logo == true %>

                              <%= f.check_box :is_logo %>
                              <%#= f.check_box_tag "site_image_ids[]", doc.id, {:checked => "checked"}  %>
                              <%# else %>
                              <%#= f.check_box_tag "site_image_ids[]", doc.id %>
                              <%# end %>

                            </td>
                            <td><%= image_tag doc.image.url, :width => "50", :class => "pull-right" %></td>
                            <td><%= link_to doc.image_file_name , doc.image.url(:original, false) %></td>
                            <td><%= doc.image_updated_at %></td>
                          </tr>
                      <% end %>
                  <% end %>
                </table>
                <%= submit_tag "Update logos" %>
            <% end %>






            <%= simple_form_for @new_site_image do |form| %>
                <%= form.hidden_field :imageable_id, :value => @post.id %>
                <%= form.hidden_field :imageable_type, :value => 'post' %>
                <%= form.input :image, as: :file %>
                <%= form.button :submit, :value => 'Upload Image', :class => "mb-sm btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
      <!-- End images -->




      <h3>Comments and Ratings</h3>

      <% @comments.each do |comment| %>
          <div class="people-say margin-bottom-20">
            <div class="overflow-h">
              <span><a href="#"> <%= comment.user.email %></a></span>
              <small class="hex pull-right"><%= comment.created_at %></small>

              <p><%= comment.body %></p>
              <%#= comment.commentable_type %>

            </div>
          </div>
      <% end %> <!-- end show comments -->



      <div class="alert alert-info fade in">

        <% if current_user %>



                <%= simple_form_for @new_comment do |f| %>
                    <%= f.hidden_field :commentable_id, :value => @post.id %>
                    <%= f.hidden_field :commentable_type, :value => 'post' %>
                    <%= f.text_area :body, :class => "form-control", :rows => "7" %>
                    <%= f.submit 'Submit' %>
                <% end %>


        <% end %>
      </div>








    </div>

    <!-- Blog Sidebar Widgets Column -->
    <div class="col-md-4">





      <div class="imagepanel">
        <% @postimages.each do |img| %>
            <%= image_tag(img.image.url(:original, false), :class => "img-responsive") %>
        <% end %>

      </div>



      <!-- Blog Search Well -->
      <div class="well">

      </div>

      <!-- Blog Categories Well -->


    </div>

  </div>
  <!-- /.row -->

  <hr>

</div>
<!-- /.container -->