config/routes.rb
Rails.application.routes.draw do

  resources :dbfields
  resources :dbtables
  resources :requests
  resources :sections
  resources :chapters
  resources :books

  #resources :searches
  resources :resources
  resources :site_images
  resources :site_documents
  resources :post_documents
  devise_for :users
  resources :posts
  resources :comments, :path_prefix => '/:commentable_type/:commentable_id'

  get 'publish', to: 'visitors#publish', as: 'publish'
  get 'moveup', to: 'sections#moveup', as: 'moveup'
  get 'movedown', to: 'sections#movedown', as: 'movedown'
  get 'staffguide', to: 'visitors#staff_guide', as: 'staffguide'
  get 'granteeguide', to: 'visitors#grantee_guide', as: 'granteeguide'
  get 'adminguide', to: 'visitors#admin_guide', as: 'adminguide'
  get 'submit', to: 'requests#submit', as: 'submit'
  get 'requestdash', to: 'requests#dashboard', as: 'requestdash'
  root 'requests#index'


  resources :users

end

app/models/site_document.rb
class SiteDocument < ActiveRecord::Base
  translates :name
  belongs_to :language
  has_attached_file :document

end

app/controllers/site_documents_controller.rb
class SiteDocumentsController < ApplicationController
  before_action :set_site_document, only: [:show, :edit, :update, :destroy]

  # GET /site_documents
  # GET /site_documents.json
  def index
    @site_documents = SiteDocument.all
  end

  # GET /site_documents/1
  # GET /site_documents/1.json
  def show
  end

  # GET /site_documents/new
  def new
    @site_document = SiteDocument.new
  end

  # GET /site_documents/1/edit
  def edit
  end

  # POST /site_documents
  # POST /site_documents.json
  def create

    @site_document = SiteDocument.new(site_document_params)
    dtype = @site_document.documentable_type
    did = @site_document.documentable_id
    if dtype == 'post'
      d = Post.find(did)
    elsif dtype == 'request'
      d = Request.find(did)
    elsif dtype == 'series'
      d = Series.find(did)
    end





    respond_to do |format|
      if @site_document.save
        format.html { redirect_to d, notice: 'Site document was successfully created.' }
        format.json { render :show, status: :created, location: @site_document }
      else
        format.html { render :new }
        format.json { render json: @site_document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /site_documents/1
  # PATCH/PUT /site_documents/1.json
  def update


    respond_to do |format|
      if @site_document.update(site_document_params)
        format.html { redirect_to @site_document, notice: 'Site document was successfully updated.' }
        format.json { render :show, status: :ok, location: @site_document }
      else
        format.html { render :edit }
        format.json { render json: @site_document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /site_documents/1
  # DELETE /site_documents/1.json
  def destroy
    @site_document.destroy
    respond_to do |format|
      format.html { redirect_to site_documents_url, notice: 'Site document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site_document
      @site_document = SiteDocument.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_document_params
      params.require(:site_document).permit(:name, :documentable_type, :documentable_id, :document)
    end
end

app/helpers/site_documents_helper.rb
module SiteDocumentsHelper
end

app/views/site_documents/_form.html.erb
<%= form_for @site_document, url: users_path, html: { multipart: true } do |f| %>
    <%= hidden_field_tag :locale, I18n.locale %>
<%#= form_for(@site_document) do |f| %>
  <% if @site_document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site_document.errors.count, "error") %> prohibited this site_document from being saved:</h2>

      <ul>
      <% @site_document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

    <%= f.file_field :document %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/site_documents/edit.html.erb
<h1>Editing Site Document</h1>

<%= render 'form' %>

<%= link_to 'Show', @site_document %> |
<%= link_to 'Back', site_documents_path %>

app/views/site_documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Site Documents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @site_documents.each do |site_document| %>
      <tr>
        <td><%= site_document.name %></td>
        <td><%= link_to 'Show', site_document %></td>
        <td><%= link_to 'Edit', edit_site_document_path(site_document) %></td>
        <td><%= link_to 'Destroy', site_document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Site document', new_site_document_path %>

app/views/site_documents/new.html.erb
<h1>New Site Document</h1>

<%= render 'form' %>

<%= link_to 'Back', site_documents_path %>

app/views/site_documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @site_document.name %>
</p>

<%= link_to 'Edit', edit_site_document_path(@site_document) %> |
<%= link_to 'Back', site_documents_path %>